name: Go package

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, reopened, edited]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.18'

      - name: Go to Dir
        run: cd unittest

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test ./... -coverprofile coverage.out && go tool cover -func coverage.out